# Generated by Django 5.0.6 on 2024-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='snippet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
