# Generated by Django 5.0.6 on 2024-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_news_link_alter_news_snippet_alter_news_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='website',
        ),
        migrations.AddField(
            model_name='news',
            name='site_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
