# Generated by Django 5.0.6 on 2024-05-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_news_search_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='search_timestamp',
        ),
    ]
