# Generated by Django 5.0.6 on 2024-05-24 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_remove_news_search_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='search_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
